source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
include: ['.htaccess', 'BingSiteAuth.xml']
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - sitemap.xml
  - .asset_pipeline
  - .asset_pipeline/
  - .asset_pipeline/assets/
  - source/.asset_pipeline/assets/
plugins:
  - jekyll-paginate
  - jekyll-sitemap

url: https://libcloud.apache.org
domain: libcloud.apache.org
title: Apache Libcloud
headline: Python library that abstracts away differences among multiple cloud provider APIs
description: Apache Libcloud is a Python library that abstracts away differences among multiple cloud provider APIs
author: The Apache Software Foundation
keywords:
  - python
  - libcloud
  - cloud
  - cloud computing
  - rackspace
  - amazon ec2
  - cloudfiles
  - openstack
  - cloudstack
timezone: UTC

lsi:         false
highlighter: rouge
permalink: blog/:year/:month/:day/:title.html

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  hard_wrap: false
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

paginate: 5
paginate_path: blog/page/:num

tag_page_layout: tag_page
tag_page_dir: blog/tags

asset_pipeline:
  # NOTE: jquery >= 3.4.0 doesn't work with compress: true, likely bug in old version of
  # compressor
  bundle: true # Default = true
  compress: true # Default = true
  output_path: assets     # Default = assets
  #display_path: nil       # Default = nil
  # NOTE: This needs to be outside source site otherwise jekyll watch process will end up
  # in re-generation loop when this directory is updated
  staging_path: "../.asset_pipeline"
  gzip: true # Default = false

gravatar:
  size: 120
  secure: true
  default_image: mm

lunr_excludes: [tags/.*\.html]

# Archive plugin settings
archive_dir: blog/archives

# Site specific stuff
navigation:
- text: Home
  url: /
- text: About
  url: /about.html
- text: Quick Start
  url: /getting-started.html
- text: Documentation
  url: https://libcloud.readthedocs.org/en/stable/
  external: true
- text: Downloads
  url: /downloads.html
- text: Community
  url: /community.html
- text: Blog
  url: /blog/
